(define (expt b n)
  (define (even? k)
    (= (remainder k 2) 0))
  (define (square k)
    (* k k))
  (define (expt-iter i)
    (cond ((= i 0) 1)
          ((even? i) (square (expt-iter (/ i 2))))
          (else (* (square (expt-iter (/ (- i 1) 2)))
                   b))))
  (expt-iter n))
