(define (integral f a b n)
  (define step-size (/ (- b a) (* n 1.0)))
  (define (next-coefficient k)
    (cond ((= k 4) 2)
          ((= k 2) 4)))
  (define (integral-iter c k)
    (if (>= c b)
      0
      (+ (* k (f c))
         (integral-iter (+ c step-size) (next-coefficient k)))))
  (* (/ step-size 3.0)
     (+ (f a)
        (integral-iter (+ a step-size) 4)
        (f b))))
